'use client'

import { useState, useTransition, useRef } from 'react'
import { useRouter } from 'next/navigation'
import {
  Wand2, Loader2, CheckCircle, Download, Tag,
  FileText, ChevronDown, AlertCircle, Eye, EyeOff,
  Save, RotateCcw,
} from 'lucide-react'

type Category = { id: string; name: string; slug: string }

type GeneratedArticle = {
  title: string
  slug: string
  body: string
}

const TONES = [
  'Professional & Technical',
  'Exciting & Viral',
  'Opinionated & Analytical',
  'Neutral & Informative',
  'Conversational & Accessible',
]

// ─────────────────────────────────────────────────────────────
// PDF Download helper (no external library needed)
// ─────────────────────────────────────────────────────────────
function downloadAsPdf(article: GeneratedArticle) {
  // Build a self-contained HTML document and print-to-PDF via browser
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${article.title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: Georgia, 'Times New Roman', serif;
      max-width: 780px;
      margin: 40px auto;
      padding: 0 32px;
      color: #1a1a1a;
      line-height: 1.75;
    }
    header {
      border-bottom: 3px solid #1e40af;
      padding-bottom: 20px;
      margin-bottom: 32px;
    }
    .brand {
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 0.15em;
      text-transform: uppercase;
      color: #1e40af;
      margin-bottom: 12px;
    }
    h1 {
      font-size: 28px;
      font-weight: 800;
      line-height: 1.3;
      color: #0f172a;
      margin-bottom: 10px;
    }
    .meta {
      font-size: 12px;
      color: #64748b;
    }
    .slug {
      font-size: 11px;
      color: #94a3b8;
      font-family: monospace;
      margin-top: 4px;
    }
    .body-content { margin-top: 24px; }
    .body-content h2 {
      font-size: 20px;
      font-weight: 700;
      color: #0f172a;
      margin: 28px 0 10px;
    }
    .body-content h3 {
      font-size: 17px;
      font-weight: 600;
      color: #1e293b;
      margin: 22px 0 8px;
    }
    .body-content p { margin-bottom: 14px; font-size: 15px; }
    .body-content ul, .body-content ol {
      padding-left: 22px;
      margin-bottom: 14px;
    }
    .body-content li { margin-bottom: 6px; font-size: 15px; }
    .body-content blockquote {
      border-left: 4px solid #1e40af;
      padding-left: 16px;
      color: #475569;
      font-style: italic;
      margin: 18px 0;
    }
    footer {
      margin-top: 48px;
      padding-top: 16px;
      border-top: 1px solid #e2e8f0;
      font-size: 11px;
      color: #94a3b8;
    }
    @media print {
      body { margin: 0; padding: 24px; }
    }
  </style>
</head>
<body>
  <header>
    <p class="brand">Blorix — AI Generated Draft</p>
    <h1>${article.title}</h1>
    <p class="meta">Generated on ${new Date().toLocaleDateString('en-IN', {
      day: 'numeric', month: 'long', year: 'numeric',
    })} · Status: Pending Review</p>
    <p class="slug">Slug: /${article.slug}</p>
  </header>
  <div class="body-content">
    ${article.body}
  </div>
  <footer>
    Generated by Blorix AI Writer · This is a draft for editorial review only.
  </footer>
</body>
</html>`

  const blob = new Blob([htmlContent], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const printWindow = window.open(url, '_blank')
  if (printWindow) {
    printWindow.onload = () => {
      printWindow.print()
      setTimeout(() => URL.revokeObjectURL(url), 2000)
    }
  }
}

// ─────────────────────────────────────────────────────────────
// Main Form
// ─────────────────────────────────────────────────────────────
export default function AIWriterForm({ categories }: { categories: Category[] }) {
  const router = useRouter()
  const [isPending, startTransition] = useTransition()

  // Form state
  const [categoryId, setCategoryId] = useState(categories[0]?.id ?? '')
  const [prompt, setPrompt] = useState('')
  const [tone, setTone] = useState(TONES[0])

  // Output state
  const [article, setArticle] = useState<GeneratedArticle | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [previewMode, setPreviewMode] = useState(true)
  const [saved, setSaved] = useState(false)

  const outputRef = useRef<HTMLDivElement>(null)

  const selectedCategory = categories.find((c) => c.id === categoryId)

  // ── Generate ──────────────────────────────────────────────
  const handleGenerate = () => {
    if (!prompt.trim()) return
    setError(null)
    setArticle(null)
    setSaved(false)

    startTransition(async () => {
      try {
        const res = await fetch('/api/generate/custom', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'x-admin-call': '1' },
          body: JSON.stringify({
            categoryId,
            categorySlug: selectedCategory?.slug ?? '',
            categoryName: selectedCategory?.name ?? '',
            prompt: prompt.trim(),
            tone,
          }),
        })

        const json = await res.json()
        if (!res.ok) {
          setError(json.error ?? 'Generation failed. Please try again.')
          return
        }

        setArticle(json.article)
        // Scroll to output
        setTimeout(() => outputRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100)
      } catch (err: any) {
        setError(err.message ?? 'Network error. Please try again.')
      }
    })
  }

  // ── Save to DB as PENDING_REVIEW ──────────────────────────
  const handleSave = () => {
    if (!article) return
    setSaved(false)

    startTransition(async () => {
      try {
        const res = await fetch('/api/generate/save', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'x-admin-call': '1' },
          body: JSON.stringify({ article, categoryId }),
        })

        const json = await res.json()
        if (!res.ok) {
          setError(json.error ?? 'Failed to save article.')
          return
        }
        setSaved(true)
        router.refresh()
      } catch (err: any) {
        setError(err.message ?? 'Network error.')
      }
    })
  }

  // ── Reset ─────────────────────────────────────────────────
  const handleReset = () => {
    setArticle(null)
    setError(null)
    setSaved(false)
    setPrompt('')
  }

  return (
    <div className="space-y-6">
      {/* ── Composer Card ─────────────────────────────────── */}
      <div className="bg-white rounded-3xl border border-gray-200 shadow-sm p-8 space-y-6">
        <h2 className="text-base font-bold text-gray-800">Compose Your Prompt</h2>

        {/* Category + Tone row */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

          {/* Category selector */}
          <div className="space-y-1.5">
            <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest">
              Category
            </label>
            <div className="relative">
              <Tag className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
              <select
                value={categoryId}
                onChange={(e) => setCategoryId(e.target.value)}
                disabled={isPending}
                className="w-full appearance-none bg-gray-50 border border-gray-200 rounded-2xl pl-10 pr-10 py-3 text-sm font-semibold text-gray-900 outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 transition-all disabled:opacity-60"
              >
                {categories.length === 0 && (
                  <option value="">No categories — add one first</option>
                )}
                {categories.map((cat) => (
                  <option key={cat.id} value={cat.id}>
                    {cat.name}
                  </option>
                ))}
              </select>
              <ChevronDown className="absolute right-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
            </div>
            {selectedCategory && (
              <p className="text-[11px] text-gray-400 font-mono pl-1">slug: /{selectedCategory.slug}</p>
            )}
          </div>

          {/* Tone selector */}
          <div className="space-y-1.5">
            <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest">
              Tone of Voice
            </label>
            <div className="relative">
              <select
                value={tone}
                onChange={(e) => setTone(e.target.value)}
                disabled={isPending}
                className="w-full appearance-none bg-gray-50 border border-gray-200 rounded-2xl px-4 py-3 pr-10 text-sm font-semibold text-gray-900 outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 transition-all disabled:opacity-60"
              >
                {TONES.map((t) => (
                  <option key={t}>{t}</option>
                ))}
              </select>
              <ChevronDown className="absolute right-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
            </div>
          </div>
        </div>

        {/* Prompt textarea */}
        <div className="space-y-1.5">
          <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest">
            Your Prompt
            <span className="ml-2 text-[10px] font-normal text-gray-400 normal-case tracking-normal">
              Describe exactly what you want the article to cover
            </span>
          </label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            disabled={isPending}
            rows={8}
            placeholder={`e.g. Write a detailed news article about the launch of Tata Curvv EV in India — cover pricing, battery range, key competitors, and how it positions Tata in the EV segment. Include expert opinions and market context.`}
            className="w-full p-5 border border-gray-200 rounded-2xl focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all text-gray-800 text-[15px] leading-relaxed resize-y min-h-[200px] disabled:opacity-60 placeholder-gray-300"
          />
          <div className="flex justify-between items-center px-1">
            <p className="text-[11px] text-gray-400">
              Be specific — the more context you give, the better the output.
            </p>
            <p className="text-[11px] text-gray-400 tabular-nums">
              {prompt.length} chars
            </p>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-3 pt-2">
          <button
            onClick={handleGenerate}
            disabled={isPending || !prompt.trim() || categories.length === 0}
            className="flex-1 py-4 bg-gray-900 hover:bg-black disabled:opacity-50 text-white rounded-2xl font-bold flex items-center justify-center gap-2 transition-all shadow-xl shadow-gray-900/20 group"
          >
            {isPending ? (
              <Loader2 className="w-5 h-5 animate-spin" />
            ) : (
              <Wand2 className="w-5 h-5 group-hover:rotate-12 transition-transform" />
            )}
            {isPending ? 'Generating…' : 'Generate Article'}
          </button>

          {article && (
            <button
              onClick={handleReset}
              title="Start over"
              className="p-4 bg-gray-100 hover:bg-gray-200 text-gray-600 rounded-2xl transition-colors"
            >
              <RotateCcw className="w-5 h-5" />
            </button>
          )}
        </div>

        {/* Error state */}
        {error && (
          <div className="flex items-start gap-3 p-4 bg-red-50 border border-red-200 rounded-2xl">
            <AlertCircle className="w-4 h-4 text-red-500 mt-0.5 shrink-0" />
            <p className="text-sm text-red-700 font-medium">{error}</p>
          </div>
        )}
      </div>

      {/* ── Generated Output ──────────────────────────────── */}
      {article && (
        <div ref={outputRef} className="bg-white rounded-3xl border border-gray-200 shadow-sm overflow-hidden">

          {/* Output header bar */}
          <div className="flex items-center justify-between px-7 py-4 bg-emerald-50 border-b border-emerald-100">
            <div className="flex items-center gap-2">
              <CheckCircle className="w-5 h-5 text-emerald-600" />
              <span className="text-sm font-bold text-emerald-800">Article Generated Successfully</span>
            </div>
            <div className="flex items-center gap-2">
              {/* Preview toggle */}
              <button
                onClick={() => setPreviewMode(!previewMode)}
                className={`flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg transition-colors ${
                  previewMode
                    ? 'bg-gray-900 text-white'
                    : 'bg-white text-gray-600 hover:bg-gray-100 border border-gray-200'
                }`}
              >
                {previewMode ? <Eye className="w-3.5 h-3.5" /> : <EyeOff className="w-3.5 h-3.5" />}
                {previewMode ? 'Preview' : 'Raw'}
              </button>

              {/* Download PDF */}
              <button
                onClick={() => downloadAsPdf(article)}
                className="flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg bg-white text-gray-700 hover:bg-gray-100 border border-gray-200 transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                Download PDF
              </button>

              {/* Save to review queue */}
              <button
                onClick={handleSave}
                disabled={isPending || saved}
                className={`flex items-center gap-1.5 text-xs font-semibold px-4 py-1.5 rounded-lg transition-all ${
                  saved
                    ? 'bg-emerald-600 text-white cursor-default'
                    : 'bg-blue-600 hover:bg-blue-700 text-white shadow-md shadow-blue-600/20 disabled:opacity-60'
                }`}
              >
                {isPending ? (
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                ) : saved ? (
                  <CheckCircle className="w-3.5 h-3.5" />
                ) : (
                  <Save className="w-3.5 h-3.5" />
                )}
                {saved ? 'Saved to Queue' : 'Save to Review Queue'}
              </button>
            </div>
          </div>

          {/* Article meta */}
          <div className="px-7 pt-6 pb-2 border-b border-gray-100 space-y-1">
            <h2 className="text-xl font-black text-gray-900 leading-snug">{article.title}</h2>
            <div className="flex items-center gap-3 flex-wrap">
              <span className="text-xs font-semibold text-violet-600 bg-violet-50 border border-violet-100 px-2.5 py-1 rounded-lg">
                AI Generated
              </span>
              {selectedCategory && (
                <span className="text-xs font-semibold text-blue-600 bg-blue-50 border border-blue-100 px-2.5 py-1 rounded-lg">
                  {selectedCategory.name}
                </span>
              )}
              <span className="text-xs text-gray-400 font-mono">slug: /{article.slug}</span>
            </div>
          </div>

          {/* Body */}
          <div className="px-7 py-6">
            {previewMode ? (
              <div
                className="prose prose-slate max-w-none text-[15px] leading-relaxed
                  [&_h2]:text-xl [&_h2]:font-bold [&_h2]:text-gray-900 [&_h2]:mt-6 [&_h2]:mb-3
                  [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:text-gray-800 [&_h3]:mt-5 [&_h3]:mb-2
                  [&_p]:text-gray-700 [&_p]:mb-4 [&_p]:leading-7
                  [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:mb-4 [&_ul]:text-gray-700
                  [&_ol]:list-decimal [&_ol]:pl-6 [&_ol]:mb-4
                  [&_li]:mb-2 [&_li]:text-gray-700
                  [&_strong]:font-bold [&_em]:italic
                  [&_blockquote]:border-l-4 [&_blockquote]:border-blue-500 [&_blockquote]:pl-4 [&_blockquote]:italic [&_blockquote]:text-gray-600 [&_blockquote]:my-4"
                dangerouslySetInnerHTML={{ __html: article.body }}
              />
            ) : (
              <pre className="text-xs text-gray-600 bg-gray-50 border border-gray-100 rounded-2xl p-5 whitespace-pre-wrap font-mono leading-relaxed overflow-auto max-h-[500px]">
                {article.body}
              </pre>
            )}
          </div>

          {/* Bottom save reminder */}
          {!saved && (
            <div className="flex items-center justify-between px-7 py-4 bg-amber-50 border-t border-amber-100">
              <p className="text-xs text-amber-700 font-medium">
                💡 Save to queue so it appears in <strong>AI Review</strong> for editorial approval before publishing.
              </p>
              <button
                onClick={handleSave}
                disabled={isPending}
                className="flex items-center gap-1.5 text-xs font-bold px-4 py-2 bg-amber-600 hover:bg-amber-700 text-white rounded-xl transition-colors disabled:opacity-60"
              >
                <Save className="w-3.5 h-3.5" />
                Save Now
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
